SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[Execute_For_ACTS_Consumer]
AS
BEGIN

IF NOT EXISTS(SELECT * FROM sys.database_principals WHERE name = 'insert_synapse_name')
  BEGIN
    CREATE USER [insert_synapse_name] FROM EXTERNAL PROVIDER;
  END

GRANT SELECT ON OBJECT::[dbo].[IngestedLandingDataAudit]
    TO [insert_synapse_name];

DECLARE @controlTableRecords INTEGER 

SET @controlTableRecords = (SELECT COUNT(*) FROM [dbo].[ControlTable] 
                            WHERE [SourceObjectSettings] = '{ "fileName": "Fact-Taxpayersatisfactiondetail%.csv", "folderPath": "%/%", "container": "landing" }')

IF @controlTableRecords = 0
BEGIN
INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "All%Data%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/AllData/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Corruption_Data%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/CorruptionData/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Fact%Invoices%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/FactInvoices/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Fact-Taxpayersatisfactiondetail%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/FactTaxPayerSatisfactionDetail/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "FactInvoicedetails%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/FactInvoiceDetails/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "TaxGapByBusinessType.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/TaxGapByBusinessType/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "TaxGapByRegion.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/TaxGapByRegion/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "VAT_Daily%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/VATDaily/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "fact-monthly.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/FactMonthly/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "fact-pbiMonthlyTaxDetails%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/FactPbiMonthlyTaxDetails/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "pbiTaxDetailMonthly.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/pbiTaxDetailMonthly/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "VAT Bottom Charts.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/VatChartData/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Country_Values.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/Country/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "TargetFactorsbyMonth.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/TargetFactorsbyMonth/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "AuditorStateSupervisor.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/AuditorStateSupervisor/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "AxisTable.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/Axis/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Anomalies.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/AnomaliesMonth/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "dailytaxdetails%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/DailyTaxDetails/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

INSERT [dbo].[ControlTable] ([SourceObjectSettings], [SourceConnectionSettingsName], [CopySourceSettings], [SinkObjectSettings], [SinkConnectionSettingsName], [CopySinkSettings], [CopyActivitySettings], [TopLevelPipelineName], [TriggerName], [DataLoadingBehaviorSettings], [TaskId], [CopyEnabled], [DataContract]) VALUES (N'{ "fileName": "Campaign_Analytics%.csv", "folderPath": "%/%", "container": "landing" }', N'', N'{ "fileType": "delimitedText", "delimiter": ",", "compression": "None"}', N'{ "fileName": null, "folderPath": "Tax/TaxData/CampaignAnalytics/", "container": "raw" }', N'', N'', N'', N'PL_2_Process_Landed_Files_Step2', N'TR_blobCreatedEvent', N'{ "dataLoadingBehavior": "Copy_to_Raw", "loadType": "full" }', 0, 1, N'{}')

END

END
GO
